name: ci

on:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: install dependencies
        run: npm install

      - name: lint site
        run: npm run lint

      - name: build site
        run: npm run build
