name: Deploy to Staging
on:
  push:
    branches:
      - stage
jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - uses: actions/checkout@v2
      - name: Login to GCR
        uses: docker/login-action@v1
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.GOOGLE_CREDENTIALS }}
      - name: Build and push amplication/blog Docker image
        uses: docker/build-push-action@v2
        with:
          pull: true
          push: true
          tags: |
            gcr.io/amplication/blog:${{ github.sha }}
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false
      - name: Terraform Init
        run: terraform init -backend-config="prefix=amplication-blog/staging"
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        working-directory: terraform
      - name: Terraform Apply
        run: terraform apply -auto-approve -lock-timeout=1200s --var-file=environments/staging.tfvars
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
          TF_VAR_image: gcr.io/amplication/blog:${{ github.sha }}
          TF_VAR_hubspot_api_key: ${{ secrets[format('{0}_hubspot_api_key', 'staging')] }}
        working-directory: terraform
