name: Tests
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Install dependencies
        run: npm i
      - name: Lint site
        run: npm run lint
      - name: Build site
        run: npm run build
